### ISSUE TITLE
Warning: Added non-passive event listener to a scroll-blocking 'wheel' event.

### ISSUE THREAD

**Issue by FrancescoBorzi** [scttcper/ngx-github-buttons#220]
Since I added the star button, I get the following warning:

> [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by scttcper** [comment]
i don't believe this adds any listeners
